name: Verify Dockerfile REFRESHED_AT Updated

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

permissions: {}

jobs:
  verify-dockerfiles:
    name: Verify Dockerfiles REFRESHED_AT Updated
    permissions:
      contents: read
    uses: senzing-factory/build-resources/.github/workflows/verify-dockerfile-refreshed-at-updated.yaml@v3
